apiVersion: ray.io/v1
kind: RayService
metadata:
  name: ray-service-test
  namespace: ray-test
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path:  ray-operator.config.samples.vllm.serve:model
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
        ray_actor_options:
          num_cpus: 2
          # NOTE: num_gpus is set automatically based on TENSOR_PARALLELISM
      runtime_env:
        working_dir: "https://github.com/jannikstdl/kuberay/archive/master.zip"
        pip: ["vllm==0.6.3"]
        env_vars:
          MODEL_ID: "Qwen/Qwen2.5-0.5B-Instruct-AWQ"
          TENSOR_PARALLELISM: "1"
          PIPELINE_PARALLELISM: "2"
          MAX_MODEL_LEN: "1024"
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray-ml:2.33.0.914af0-py311
              resources:
                limits:
                  cpu: "2"
                  memory: "8Gi"
                  ephemeral-storage: "20Gi"
                requests:
                  cpu: "2"
                  memory: "8Gi"
                  ephemeral-storage: "10Gi"
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - replicas: 2
        minReplicas: 0
        maxReplicas: 2
        groupName: gpu-group
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: llm
                image: rayproject/ray-ml:2.33.0.914af0-py311
                resources:
                  limits:
                    cpu: "2"
                    memory: "20Gi"
                    nvidia.com/gpu: "1"
                    ephemeral-storage: "20Gi"
                  requests:
                    cpu: "2"
                    memory: "20Gi"
                    nvidia.com/gpu: "1"
                    ephemeral-storage: "10Gi"
            # Please add the following taints to the GPU node.
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Exists"
                effect: "NoSchedule"
